import fs from 'fs/promises';
import path from 'path';

const SOURCE_GRAPH = path.join(process.cwd(), 'curriculum', 'topics', 'topics_mathematics_jhs3_with_graph.json');
const DEST_GRAPH_JS = path.join(process.cwd(), 'public', 'js', 'data', 'topicGraph.js');

// Helper to normalize and enrich the graph
function normalizeGraph(root) {
  const subject = root.subject;

  // Recursive traversal
  function traverse(node, currentLevel) {
    if (node.class) currentLevel = node.class;

    // Add metadata to leaf topics
    if (node.id) {
      node.subject = subject;
      node.class = currentLevel;

      // Normalize foundations/next to string arrays
      if (node.foundations) {
        node.foundations = node.foundations.map(f => (typeof f === 'object' && f.id) ? f.id : f);
      }
      if (node.next) {
        node.next = node.next.map(n => (typeof n === 'object' && n.id) ? n.id : n);
      }
    }

    if (node.levels) node.levels.forEach(child => traverse(child, currentLevel));
    if (node.strands) node.strands.forEach(child => traverse(child, currentLevel));
    if (node.substrands) node.substrands.forEach(child => traverse(child, currentLevel));
    if (node.topics) node.topics.forEach(child => traverse(child, currentLevel));
  }

  traverse(root, null);
  return root;
}

async function syncGraph() {
  try {
    console.log("Reading generated graph...");
    const graphData = JSON.parse(await fs.readFile(SOURCE_GRAPH, 'utf-8'));

    const normalizedData = normalizeGraph(graphData);

    // Wrap in JS export
    const jsContent = `// Auto-generated by scripts/sync_frontend_graph.js
export const TOPIC_GRAPH = ${JSON.stringify(normalizedData, null, 2)};

export function getTopicById(topicId) {
  if (!topicId) return null;
  // DFS search
  const stack = [TOPIC_GRAPH];
  while (stack.length > 0) {
    const node = stack.pop();
    if (node.id === topicId) return node;
    
    // Check children containers
    if (node.levels) stack.push(...node.levels);
    if (node.strands) stack.push(...node.strands);
    if (node.substrands) stack.push(...node.substrands);
    if (node.topics) stack.push(...node.topics);
  }
  return null;
}
`;

    await fs.writeFile(DEST_GRAPH_JS, jsContent);
    console.log("✅ Successfully synced topicGraph.js to frontend.");

  } catch (error) {
    console.error("❌ Error syncing graph:", error);
  }
}

syncGraph();
